cicd1

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,56 +1,47 @@
-name: Main workflow
+name: Deploy puppeteer to VPS Docker
+
 on:
   push:
     branches:
-      - main
-env:
-  WORKSPACE: /home/backend
-  PROJECT_NAME: nest-docker-vps-cicd
+      - master
+
 jobs:
   deploy:
-    name: Go To Production
-    runs-on: self-hosted
+    runs-on: ubuntu-latest
+
     steps:
-      - name: If Folder Not Found Clone
-        run: |
-          # Tạo thư mục nếu nó không tồn tại
-          if [ ! -d "$WORKSPACE/$PROJECT_NAME" ]; then
-            mkdir -p "$WORKSPACE/$PROJECT_NAME"
-            cd "$WORKSPACE"
-            git clone https://${{ secrets.GH_TOKEN }}@github.com/trungthanh12081997/$PROJECT_NAME.git
-          else
-            echo "Directory already exists: $WORKSPACE/$PROJECT_NAME"
-          fi
-        shell: bash
-        env:
-          WORKSPACE: /home/backend
-          PROJECT_NAME: nest-docker-vps-cicd
+    - name: Checkout code
+      uses: actions/checkout@v2
 
-      - name: Deploy
-        run: |
-          echo "Deploying"
-          cd "$WORKSPACE/$PROJECT_NAME"
-          git config credential.helper '!f() { sleep 1; echo "username=${{ secrets.GH_USER }}"; echo "password=${{ secrets.GH_TOKEN }}"; }; f'
-          git checkout main
-          git pull --force
+    - name: Set up Docker Buildx
+      uses: docker/setup-buildx-action@v2
 
-          CONTAINER_EXISTS=$(docker-compose -f docker-compose.yml ps -q)
-          if [ -n "$CONTAINER_EXISTS" ]; then
-            IMAGE_NAME="${{ env.PROJECT_NAME }}"
+    - name: Build Docker image for Backend
+      run: docker build -t pp_img .
 
-            # Lấy ID của container từ image
-            CONTAINER_ID=$(docker ps -q --filter "ancestor=$IMAGE_NAME")
-            echo "CONTAINER ID : $CONTAINER_ID"
-            if [ -n "$CONTAINER_ID" ]; then
-              docker stop $CONTAINER_ID
-              docker rm $CONTAINER_ID 
-              docker image rm $IMAGE_NAME
-            else
-              echo "No containers found for image $IMAGE_NAME"
-            fi
-          else
-            echo "No running containers for service $IMAGE_NAME"
-          fi
+    - name: Install sshpass
+      run: sudo apt-get update && sudo apt-get install -y sshpass
 
-          docker-compose up -d
-        shell: bash
+    - name: Deploy back end to VPS
+      env:
+        VPS_IP: ${{ secrets.VPS_IP }}
+        VPS_USER: ${{ secrets.VPS_USER }}
+        PASS: ${{ secrets.PASS }}
+      run: |
+        # SSH into VPS to extract and deploy
+        sshpass -p $PASS ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_IP << EOF
+          cd /home/$VPS_USER
+          # Clone the private repository 
+          git clone https://github.com/khoidang2110/puppeteer.git puppeteer || (cd puppeteer && git pull)
+          cd puppeteer || exit
+          docker stop pp_ctn || true
+          docker rm pp_ctn || true
+          docker rmi -f pp_img || true  
+          docker build -t pp_img .
+          # docker - d chạy nodejs ngầm ko chạy lên terminal
+          docker run --restart=always -d -p 8888:8888 --name pp_ctn pp_img
+      
+          # Clean up by removing the cloned repository files
+          cd ..
+          rm -rf puppeteer
+        EOF
